name: Update Readme 
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dotnet core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100-preview.7.20366.6'
    - name: Debug Directory
      shell: bash
      run: ls
    - name: Update Readme
      shell: bash
      run: dotnet run --project ./Updater -- ${{ secrets.consumerKey }} ${{ secrets.consumerSecret }} ${{ secrets.accessToken }} ${{ secrets.accessTokenSecret }} > README.md
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic changes
        branch: master
        file_pattern: README.md
