name: Update Readme 
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dotnet core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Debug Directory
      shell: bash
      run: ls ${{ github.workspace }}
    - name: Update Readme
      shell: bash
      working-directory: ${{ github.workspace	}}
      run: dotnet run --project ./Updater -- ${{ secrets.consumerKey }} ${{ secrets.consumerSecret }} ${{ secrets.accessToken }} ${{ secrets.accessTokenSecret }} "${{ github.workspace}}/README.md" > README.md
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic changes
        branch: master
        file_pattern: README.md
